"use strict";
// The words of the Fathers of the first centuries, from the public-domain
// translations of the Ante-Nicene and Nicene and Post-Nicene Fathers (as at New
// Advent), and two hymns of St. Ambrose newly translated from the Latin.
Object.assign(QUOTES, {
  irenaeus: [
    ["For the glory of God is a living man; and the life of man consists in beholding God.", "IV.20"],
    ["The Word of God, our Lord Jesus Christ, who did, through His transcendent love, become what we are, that He might bring us to be even what He is Himself.", "V, preface"],
    ["He who was the Son of God became the Son of man, that man, having been taken into the Word, and receiving the adoption, might become the son of God.", "III.19"],
    ["For as those who see the light are within the light, and partake of its brilliancy; even so, those who see God are in God, and receive of His splendour.", "IV.20"],
    ["For where the Church is, there is the Spirit of God; and where the Spirit of God is, there is the Church, and every kind of grace; but the Spirit is truth.", "III.24"],
    ["Offer to Him your heart in a soft and tractable state, and preserve the form in which the Creator has fashioned you.", "IV.39"],
    ["For you did not make God, but God you.", "IV.39"],
    ["God indeed makes, but man is made; and truly, He who makes is always the same; but that which is made must receive both beginning, and middle, and addition, and increase.", "IV.11"],
    ["For the Father is the invisible of the Son, but the Son the visible of the Father.", "IV.6"],
    ["The Church, having received this preaching and this faith, although scattered throughout the whole world, yet, as if occupying but one house, carefully preserves it.", "I.10"],
    ["When He became incarnate, and was made man, He commenced afresh the long line of human beings, and furnished us, in a brief, comprehensive manner, with salvation.", "III.18"],
  ].map(([t, s]) => ({ t, s: "Against Heresies " + s + ", tr. Roberts & Rambaut" })),
  hilary: [
    ["For though the splendour of His eternal glory overtax our mind's best powers, it cannot fail to see that He is beautiful.", "I"],
    ["Being infinite He is present in all things, in Him Who is infinite all are included.", "I"],
    ["For a reasonable faith is akin to reason and accepts its aid, even though that same reason cannot cope with the vastness of eternal Omnipotence.", "I"],
    ["In devout thoughts such as these my soul, engrossed in the pursuit of truth, took its delight.", "I"],
    ["In this calm assurance of safety did my soul gladly and hopefully take its rest, and feared so little the interruption of death, that death seemed only a name for eternal life.", "I"],
    ["He is infinite, for nothing contains Him and He contains all things; He is eternally unconditioned by space, for He is illimitable; eternally anterior to time, for time is His creation.", "II"],
    ["Nothing can be found lacking in that supreme Union which embraces, in Father, Son and Holy Spirit, infinity in the Eternal, His Likeness in His express Image, our enjoyment of Him in the Gift.", "II"],
    ["It is easier for me to feel this concerning the Father than to say it.", "II"],
    ["Keep, I pray You, this my pious faith undefiled, and even till my spirit departs, grant that this may be the utterance of my convictions.", "XII"],
  ].map(([t, s]) => ({ t, s: "On the Trinity " + s + ", tr. Watson & Pullan" })),
  athanasius: [
    { t: "For He was made man that we might be made God; and He manifested Himself by a body that we might receive the idea of the unseen Father.", s: "On the Incarnation of the Word, tr. Robertson" },
    { t: "And this was the wonderful thing that He was at once walking as man, and as the Word was quickening all things, and as the Son was dwelling with His Father.", s: "On the Incarnation of the Word, tr. Robertson" },
    { t: "For like the seeds which are cast into the earth, we do not perish by dissolution, but sown in the earth, shall rise again, death having been brought to nought by the grace of the Saviour.", s: "On the Incarnation of the Word, tr. Robertson" },
    { t: "For God has not only made us out of nothing; but He gave us freely, by the Grace of the Word, a life in correspondence with God.", s: "On the Incarnation of the Word, tr. Robertson" },
    { t: "The Word, then, visited that earth in which He was yet always present; and saw all these evils.", s: "On the Incarnation of the Word, tr. Robertson" },
    { t: "By the sacrifice of His own body, He both put an end to the law which was against us, and made a new beginning of life for us, by the hope of resurrection which He has given us.", s: "On the Incarnation of the Word, tr. Robertson" },
    { t: "Whence the Word of God came in His own person, that, as He was the Image of the Father, He might be able to create afresh the man after the image.", s: "On the Incarnation of the Word, tr. Robertson" },
    { t: "Nor let us think, as we look at the world, that we have renounced anything of much consequence, for the whole earth is very small compared with all the heaven.", s: "Life of Antony, tr. Ellershaw" },
    { t: "So looking up he saw the roof as it were opened, and a ray of light descending to him.", s: "Life of Antony, tr. Ellershaw" },
    { t: "But it comes so quietly and gently that immediately joy, gladness and courage arise in the soul.", s: "Life of Antony, tr. Ellershaw" },
    { t: "For joy and a settled state of soul show the holiness of him who is present.", s: "Life of Antony, tr. Ellershaw" },
  ],
  ephrem: [
    { t: "On a certain day a pearl did I take up, my brethren; I saw in it mysteries pertaining to the Kingdom; semblances and types of the Majesty; it became a fountain, and I drank out of it mysteries of the Son.", s: "The Pearl, Hymn I" },
    { t: "I found out that the Son was incomprehensible, since He is wholly Light.", s: "The Pearl, Hymn I" },
    { t: "The daughter of the sea am I, the illimitable sea!", s: "The Pearl (the pearl speaks)" },
    { t: "Search out the sea, but search not out the Lord of the sea!", s: "The Pearl" },
    { t: "Shadowed forth in your beauty is the beauty of the Son, Who clothed Himself with suffering when the nails passed through Him.", s: "The Pearl" },
    { t: "The ear is the leaf: the flesh is the tree, and you in the midst of it are a fruit of light.", s: "The Pearl" },
    { t: "Light alone, of all creatures, as its Creator, is not divided; it is not barren, for that it also begets without losing thereby.", s: "The Pearl" },
    { t: "Blessed be that Child, Who gladdened Bethlehem today!", s: "On the Nativity, Hymn II" },
    { t: "Blessed be the Babe Who made manhood young again today!", s: "On the Nativity, Hymn II" },
    { t: "Blessed be the Fruit, Who lowered Himself to our famished state!", s: "On the Nativity, Hymn II" },
    { t: "Down also came the hidden Light, and from the Body rose His beauty!", s: "On the Nativity, Hymn I" },
    { t: "Today was born the Child, and His name was called Wonder!", s: "On the Nativity, Hymn I" },
    { t: "For whoever is like this clear One, wakeful and prayerful in darkness, him in this darkness visible a light unseen surrounds!", s: "On the Nativity, Hymn I" },
  ].map((q) => ({ t: q.t, s: q.s + ", tr. Morris & Johnston" })),
  basil: [
    ["A single plant, a blade of grass is sufficient to occupy all your intelligence in the contemplation of the skill which produced it.", "V"],
    ["So, with a single word and in one instant, the Creator of all things gave the boon of light to the world.", "II"],
    ["In an instant it lighted up the whole extent of the world, the North and the South, the East and the West.", "II"],
    ["Look how in a meadow this same water becomes red in one flower, purple in another, blue in this one, white in that.", "V"],
    ["The meadows were covered with deep grass, the fertile plains quivered with harvests, and the movement of the grain was like the waving of the sea.", "V"],
    ["The heavens had received the flowers of the stars, and, like two eyes, the great luminaries beautified them in concert.", "VII"],
    ["Nothing has been done without motive, nothing by chance.", "V"],
    ["Life does not engender death; darkness is not the origin of light; sickness is not the maker of health.", "II"],
    ["Darkness, we reply, did not exist in essence; it is a condition produced in the air by the withdrawal of light.", "II"],
    ["Grand phenomena do not strike us the less when we have discovered something of their wonderful mechanism.", "I"],
    ["With light the æther becomes more pleasing and the waters more limpid.", "II"],
  ].map(([t, s]) => ({ t, s: "Hexaemeron " + s + ", tr. Blomfield Jackson" })),
  cyriljer: [
    ["One and the same rain comes down upon all the world, yet it becomes white in the lily, and red in the rose, and purple in violets and hyacinths, and different and varied in each several kind.", "XVI"],
    ["First, His coming is gentle; the perception of Him is fragrant; His burden most light; beams of light and knowledge gleam forth before His coming.", "XVI"],
    ["Be the Cross our seal made with boldness by our fingers on our brow, and on everything; over the bread we eat, and the cups we drink; in our comings in, and goings out.", "XIII"],
    ["Let us then not be ashamed of the Cross of our Saviour, but rather glory in it.", "XIII"],
    ["Regard not the Laver as simple water, but rather regard the spiritual grace that is given with the water.", "III"],
    ["For water is a grand thing, and the noblest of the four visible elements of the world.", "III"],
    ["Baptism is the end of the Old Testament, and beginning of the New.", "III"],
    ["Jesus sanctified Baptism by being Himself baptized.", "III"],
    ["Faith is an eye that enlightens every conscience, and imparts understanding.", "V"],
    ["The echo is no longer around you, but within you; for the indwelling Spirit henceforth makes your mind a house of God.", "Procatechesis"],
    ["As then it is His part to plant and to water, so it is yours to bear fruit: it is God's to grant grace, but yours to receive and guard it.", "I"],
    ["After this ye hear the chanter inviting you with a sacred melody to the communion of the Holy Mysteries, and saying, O taste and see that the Lord is good.", "XXIII"],
  ].map(([t, s]) => ({ t, s: "Catechetical Lectures " + s + ", tr. Gifford" })),
  gregnaz: [
    ["Christ is born, glorify Him. Christ from heaven, go out to meet Him.", "38"],
    ["Let us become God's for His sake, since He for ours became Man.", "1"],
    ["Let us offer ourselves, the possession most precious to God, and most fitting; let us give back to the Image what is made after the Image.", "1"],
    ["The very best order of beginning every speech and action, is to begin from God, and to end in God.", "2"],
    ["I am small and great, lowly and exalted, mortal and immortal, earthly and heavenly.", "7"],
    ["We seemed to have one soul, inhabiting two bodies.", "43 (of his friend St. Basil)"],
    ["I am an instrument of God, a rational instrument, an instrument tuned and struck by that skilful artist, the Spirit.", "12"],
    ["And when I speak of God you must be illumined at once by one flash of light and by three.", "39"],
    ["Christ is illumined, let us shine forth with Him.", "39"],
    ["Light was That Godhead Which was shown upon the Mount to the disciples — and a little too strong for their eyes.", "40"],
    ["Believe that listening is always less dangerous than talking, just as learning about God is more pleasant than teaching.", "3"],
    ["Again the darkness is past; again Light is made.", "38"],
  ].map(([t, s]) => ({ t, s: "Oration " + s + ", tr. Browne & Swallow" })),
  ambrose: [
    { t: "For what is water without the cross of Christ?", s: "On the Mysteries, tr. de Romestin" },
    { t: "Consider not the bodily forms, but the grace of the Mysteries.", s: "On the Mysteries, tr. de Romestin" },
    { t: "Do you wash this living cup of yours, that in it your good works may shine and the glory of your grace be bright.", s: "On the Mysteries, tr. de Romestin" },
    { t: "For them water flowed from the rock, for you Blood flowed from Christ; water satisfied them for a time, the Blood satiates you for eternity.", s: "On the Mysteries, tr. de Romestin" },
    { t: "Let the heart within confess what the mouth utters, let the soul feel what the voice speaks.", s: "On the Mysteries, tr. de Romestin" },
    { t: "Let no persecution lessen your love, which many waters cannot quench, nor many rivers drown.", s: "On the Mysteries, tr. de Romestin" },
    { t: "Now what ought we to learn before everything else, but to be silent, that we may be able to speak?", s: "On the Duties of the Clergy I, tr. de Romestin" },
    { t: "How many have I seen to fall into sin by speaking, but scarcely one by keeping silent.", s: "On the Duties of the Clergy I, tr. de Romestin" },
    { t: "I know that most persons speak because they do not know how to keep silent.", s: "On the Duties of the Clergy I, tr. de Romestin" },
    { t: "Silence should not remain unbroken, nor should it arise from idleness.", s: "On the Duties of the Clergy I, tr. de Romestin" },
    { t: "Eternal Maker of all things, who rule the night and the day, and give the seasons their turns to lighten our weariness.", s: "Aeterne rerum Conditor (his hymn), tr. for Luminaries" },
    { t: "At the cock's crow hope returns, health flows back to the sick, the robber's dagger is sheathed, faith returns to the fallen.", s: "Aeterne rerum Conditor (his hymn), tr. for Luminaries" },
    { t: "God, Creator of all things and Ruler of the heavens, who clothe the day with lovely light, and the night with the grace of sleep.", s: "Deus Creator omnium (his hymn, which St. Augustine remembered in his grief), tr. for Luminaries" },
  ],
});
