"use strict";
// From St. John Damascene to St. Catherine of Siena: Allies' Damascene (1898), Blackwell's
// Armenian Poems (1917), Deane's Anselm (1903), Eales' Bernard, Thorold's Catherine (1907),
// and Latin newly translated for Luminaries from the old printed editions (Peter Damian, 1867;
// Albert, ed. Borgnet, 1890) and the Latin Library and Latin Wikisource texts.
Object.assign(QUOTES, {
  damascene: [
    ["Now, however, when God is seen clothed in flesh, and conversing with men, I make an image of the God whom I see.", "I"],
    ["I do not worship matter, I worship the God of matter, who became matter for my sake, and deigned to inhabit matter, who worked out my salvation through matter.", "I"],
    ["I will not cease from honouring that matter which works my salvation.", "I"],
    ["We proclaim Him also by our senses on all sides, and we sanctify the noblest sense, which is that of sight.", "I"],
    ["What a book is to the literate, that an image is to the illiterate.", "I"],
    ["The image speaks to the sight as words to the ear; it brings us understanding.", "I"],
  ].map(([t]) => ({ t, s: "On Holy Images, tr. Allies" })),
  narek: [
    ["The lips of the Christ-child are like to twin leaves; they let roses fall when he smiles tenderly.", ""],
    ["The tears of the Christ-child are pearls when he grieves; the eyes of the Christ-child are deep as the sea.", ""],
    ["Like pomegranate grains are the dimples he hath, and clustering lilies spring up in his path.", ""],
  ].map(([t]) => ({ t, s: "The Christ-Child, tr. Alice Stone Blackwell" })),
  damian: [
    ["O desert, delight of holy minds, and sweetness of the inner taste that never runs dry!", "19"],
    ["O desert, death of vices, and the kindling and the life of virtues!", "19"],
    ["O cell, storehouse of heaven's merchants, where the goods are kept that buy the land of the living!", "19"],
    ["Happy trade, where earthly things are exchanged for heavenly, and passing things for eternal!", "19"],
    ["The cell is the meeting-place of God and men.", "19"],
    ["O cell, wonderful workshop of spiritual exercise, where the soul of man restores in itself the image of its Creator, and returns to the purity of its beginning!", "19"],
    ["You are Jacob's ladder, which carries men up to heaven and brings the angels down to help them.", "19 (to the hermit's cell)"],
    ["Holy Church is whole in all, and whole in each one.", "5"],
  ].map(([t, s]) => ({ t, s: "Dominus vobiscum " + s + ", tr. for Luminaries" })),
  anselm: [
    ["Up now, slight man! flee, for a little while, thy occupations; hide thyself, for a time, from thy disturbing thoughts.", "1"],
    ["Yield room for some little time to God; and rest for a little time in him.", "1"],
    ["Enter the inner chamber of thy mind; shut out all thoughts save that of God, and such as can aid thee in seeking him; close thy door and seek him.", "1"],
    ["Teach me to seek thee, and reveal thyself to me, when I seek thee, for I cannot seek thee, except thou teach me, nor find thee, except thou reveal thyself.", "1"],
    ["Let me seek thee in longing, let me long for thee in seeking; let me find thee in love, and love thee in finding.", "1"],
    ["For I do not seek to understand that I may believe, but I believe in order to understand.", "1"],
    ["And, indeed, we believe that thou art a being than which nothing greater can be conceived.", "2"],
    ["For I have found a joy that is full, and more than full.", "26"],
  ].map(([t, s]) => ({ t, s: "Proslogium " + s + ", tr. Deane" })),
  bernard: [
    ["As honey to the mouth, as melody in the ear, as a song of gladness to the heart, is the Name of Jesus.", "Sermons on the Song of Songs 15, tr. Eales"],
    ["A book or writing has no single point of goodness for me if I do not read therein the Name of Jesus.", "Sermons on the Song of Songs 15, tr. Eales"],
    ["Let Jesus come into your heart; let His Name leap thence to your lips.", "Sermons on the Song of Songs 15, tr. Eales"],
    ["If, then, you are wise, you will show yourself rather as a reservoir than as a canal.", "Sermons on the Song of Songs 18, tr. Eales"],
    ["The reason for loving God is God; the measure is to love without measure.", "On Loving God 1, tr. for Luminaries"],
    ["I love because I love; I love that I may love.", "Sermons on the Song of Songs 83, tr. for Luminaries"],
    ["God loved us sweetly, wisely, strongly.", "Sermons on the Song of Songs 20, tr. for Luminaries"],
    ["Learn, Christian, from Christ how you are to love Christ.", "Sermons on the Song of Songs 20, tr. for Luminaries"],
    ["A cold heart cannot take in a word on fire.", "Sermons on the Song of Songs 79, tr. for Luminaries"],
    ["To the one who does not love, the language of love will be a foreign tongue.", "Sermons on the Song of Songs 79, tr. for Luminaries"],
  ].map(([t, s]) => ({ t, s })),
  anthony: [
    ["This light is the Wisdom of God the Father, which enlightens every man coming into this world.", "Septuagesima"],
    ["This light is contrition of heart: it lights up the soul, and shows it the knowledge of God, the knowledge of its own weakness, and how to tell a good man from a bad.", "Septuagesima"],
    ["By prayer we cleanse the heart of soiled thoughts; by fasting we rein in the wantonness of the flesh.", "Septuagesima"],
    ["And see how fittingly the word of God is called a seed.", "Sexagesima"],
    ["In the morning, that is, in the time of grace, which drives out the darkness of sin, sow, O preacher, the seed of the word.", "Sexagesima"],
    ["In the wheat, white within and red without, charity is shown: it keeps purity for itself, and love for its neighbour.", "Sexagesima"],
    ["They give themselves to the labour of the active life, they face danger for their neighbour, they preach eternal life by word and by example.", "Sexagesima"],
  ].map(([t, s]) => ({ t, s: "Sermon for " + s + " Sunday, tr. for Luminaries" })),
  bonaventure: [
    ["No one can be blessed unless he rises above himself, not by a climb of the body, but of the heart.", "I.1"],
    ["Prayer, then, is the mother and the source of every going-up.", "I.1"],
    ["Let no one think that reading is enough without unction, speculation without devotion, searching without wonder, looking about without delight, work without piety, knowledge without love, understanding without humility, study without the grace of God.", "Prologue 4"],
    ["The mirror set before us outside is little or nothing, unless the mirror of our mind has been wiped clean and polished.", "Prologue 4"],
    ["If you ask how these things come about, ask grace, not learning; desire, not understanding; the groaning of prayer, not the study of reading; the Bridegroom, not the teacher.", "VII.6"],
    ["Ask God, not man; darkness, not brightness; not light, but the fire that sets the whole soul aflame and carries it over into God. And that fire is God.", "VII.6"],
    ["In all his preaching Francis proclaimed peace at the beginning and at the end, wished peace in every greeting, and in every contemplation sighed for the peace of ecstasy.", "Prologue 1"],
  ].map(([t, s]) => ({ t, s: "The Journey of the Mind into God " + s + ", tr. for Luminaries" })),
  albert: [
    ["For it is not the business of natural science simply to accept what we are told, but to seek out the causes in natural things.", "On Minerals II.ii.1"],
    ["We set down the names of the stones, and their powers, as they have come to us, either by experiment or from the writings of the authors.", "On Minerals II.ii.1"],
    ["For in such matters experiment alone gives certainty.", "On Plants VI.i.1"],
    ["Some of these we test by experiment ourselves; others we report from those whom we have found to say nothing lightly unless it was proved by experiment.", "On Plants VI.i.1"],
    ["It is taste that gives the surest test of the powers of plants.", "On Plants"],
    ["I kept this shell a long time, and showed it to many.", "On Minerals II.iii"],
  ].map(([t, s]) => ({ t, s: s + ", tr. for Luminaries" })).concat([
    { t: "A man so godlike in every science that he may fitly be called the wonder and the marvel of our time.", s: "Ulrich of Strasbourg, his student, On the Highest Good, tr. for Luminaries" },
  ]),
  catherine: [
    ["Thou, oh eternal Trinity, art a deep Sea, into which the deeper I enter the more I find, and the more I find the more I seek.", ""],
    ["I confess and do not deny that Thou didst love me before I existed, and that Thy love for me is ineffable, as if Thou wast mad with love for Thy creature.", ""],
    ["Thou art the fire which ever burns without being consumed.", ""],
    ["Thou art enamoured of the beauty of Thy workmanship.", ""],
    ["The soul cannot live without love, but always wants to love something, because she is made of love, and, by love, I created her.", " (God speaking)"],
    ["I have made a Bridge of My Word, of My only-begotten Son, and this is the truth.", " (God speaking)"],
    ["Charity gives life to all the virtues, because no virtue can be obtained without charity, which is the pure love of Me.", " (God speaking)"],
    ["I have washed you, and re-created you in the Blood of My only-begotten Son, spilt with so great a fire of love.", " (God speaking)"],
  ].map(([t, s]) => ({ t, s: "The Dialogue" + s + ", tr. Thorold" })),
});
