"use strict";
// Luminaries: the words of the Doctors, for the ticker under the field.
// Every quotation is copied from a public-domain translation (named in the
// source line), or from the Latin, newly translated for this game. None is a
// popular paraphrase: if it could not be found in the text, it is not here.
const QUOTES = {
  // E. B. Pusey's translation of the Confessions (1838), from Project Gutenberg.
  augustine: [
    ["Great art Thou, O Lord, and greatly to be praised; great is Thy power, and Thy wisdom infinite.", "Confessions I"],
    ["Thou awakest us to delight in Thy praise; for Thou madest us for Thyself, and our heart is restless, until it repose in Thee.", "Confessions I"],
    ["Too late loved I Thee, O Thou Beauty of ancient days, yet ever new! too late I loved Thee!", "Confessions X"],
    ["Thou wert with me, but I was not with Thee.", "Confessions X"],
    ["Thou calledst, and shoutedst, and burstest my deafness. Thou flashedst, shonest, and scatteredst my blindness.", "Confessions X"],
    ["Thou touchedst me, and I burned for Thy peace.", "Confessions X"],
    ["Give me chastity and continency, only not yet.", "Confessions VIII (of his younger self)"],
    ["Take up and read; Take up and read.", "Confessions VIII (the child's voice in the garden)"],
    ["Thou wert more inward to me than my most inward part; and higher than my highest.", "Confessions III"],
    ["Blessed whoso loveth Thee, and his friend in Thee, and his enemy for Thee.", "Confessions IV"],
    ["My weight, is my love; thereby am I borne, whithersoever I am borne.", "Confessions XIII"],
    ["We are inflamed, by Thy Gift we are kindled; and are carried upwards; we glow inwardly, and go forwards.", "Confessions XIII"],
    ["Give what Thou enjoinest, and enjoin what Thou wilt.", "Confessions X"],
    ["Thou light of my heart, Thou bread of my inmost soul, Thou Power who givest vigour to my mind.", "Confessions I"],
    ["Narrow is the mansion of my soul; enlarge Thou it, that Thou mayest enter in. It is ruinous; repair Thou it.", "Confessions I"],
    ["I became a great riddle to myself.", "Confessions IV"],
    ["I sought what I might love, in love with loving.", "Confessions III"],
    ["I sighed, and Thou heardest me; I wavered, and Thou didst guide me; I wandered through the broad way of the world, and Thou didst not forsake me.", "Confessions VI"],
    ["When I shall with my whole self cleave to Thee, I shall no where have sorrow or labour; and my life shall wholly live, as wholly full of Thee.", "Confessions X"],
    ["I entered and beheld with the eye of my soul (such as it was), above the same eye of my soul, above my mind, the Light Unchangeable.", "Confessions VII"],
  ].map(([t, s]) => ({ t, s: s + ", tr. Pusey" })),
  // Her songs, from the Latin of the Riesencodex (as transcribed at GregoBase),
  // newly translated here; the Latin opening is shown beside each.
  hildegard: [
    ["O power of Wisdom, who circling encircled all things, gathering them into one way that has life.", "O virtus Sapientiae"],
    ["Three wings: one flies on high, the second distils from the earth, and the third flies everywhere.", "O virtus Sapientiae"],
    ["O most noble greenness, rooted in the sun.", "O nobilissima viriditas"],
    ["You blush like the dawn and burn like the flame of the sun.", "O nobilissima viriditas"],
    ["O fire of the Spirit, the Comforter, life of the life of every creature.", "O ignis Spiritus Paracliti"],
    ["You are holy, quickening the forms of things; holy, anointing the dangerously broken; holy, cleansing foul wounds.", "O ignis Spiritus Paracliti"],
    ["O breath of holiness, O fire of love, O sweet taste in our breasts.", "O ignis Spiritus Paracliti"],
    ["Love overflows into all things, from the depths to the heights beyond the stars.", "Caritas abundat"],
    ["For she has given the highest King the kiss of peace.", "Caritas abundat"],
    ["Praise to the Trinity, who is sound and life and creator of all things in their own life.", "Laus Trinitati"],
    ["O how wondrous is the foreknowledge of the divine heart, which foreknew every creature.", "O quam mirabilis"],
    ["When God looked upon the face of the man He had formed, He saw all His works whole in that same human form.", "O quam mirabilis"],
    ["O streaming blood, that rang out on high, when all the elements entwined in a voice of lament.", "O cruor sanguinis"],
    ["O leafy branch, standing in your nobility as the dawn comes forth.", "O frondens virga"],
    ["O shepherd of souls, O first voice, through whom we all were made.", "O pastor animarum"],
    ["O eternal God, may it please You now to burn in that love.", "O aeterne Deus"],
  ].map(([t, s]) => ({ t, s: s + " (her own song), tr. for Luminaries" })),
  // The Summa in the English Dominican Fathers' translation (1911–25); his
  // hymns from the Latin, newly translated; and the words he is reported to have said.
  thomas: [
    { t: "Grace does not destroy nature but perfects it.", s: "Summa Theologica I, q. 1, a. 8, tr. English Dominicans" },
    { t: "To love is to wish good to someone.", s: "Summa Theologica I-II, q. 26, a. 4 (after Aristotle), tr. English Dominicans" },
    { t: "Beautiful things are those which please when seen. Hence beauty consists in due proportion.", s: "Summa Theologica I, q. 5, a. 4, tr. English Dominicans" },
    { t: "God is in all things; not, indeed, as part of their essence, nor as an accident, but as an agent is present to that upon which it works.", s: "Summa Theologica I, q. 8, a. 1, tr. English Dominicans" },
    { t: "God loves all existing things. For all existing things, in so far as they exist, are good, since the existence of a thing is itself a good.", s: "Summa Theologica I, q. 20, a. 2, tr. English Dominicans" },
    { t: "Even as it is better to enlighten than merely to shine, so is it better to give to others the fruits of one's contemplation than merely to contemplate.", s: "Summa Theologica II-II, q. 188, a. 6, tr. English Dominicans" },
    { t: "The light of faith makes us see what we believe.", s: "Summa Theologica II-II, q. 1, a. 4, tr. English Dominicans" },
    { t: "Happiness is the reward of virtue.", s: "Summa Theologica I-II, q. 4, a. 6, tr. English Dominicans" },
    { t: "Sing, my tongue, the mystery of the glorious Body, and of the precious Blood.", s: "Pange lingua (his hymn for Corpus Christi), tr. for Luminaries" },
    { t: "The Word made flesh, by a word, makes true bread into flesh.", s: "Pange lingua, tr. for Luminaries" },
    { t: "Let faith supply what the senses lack.", s: "Tantum ergo (from Pange lingua), tr. for Luminaries" },
    { t: "Devoutly I adore Thee, hidden Godhead, who truly hidest beneath these forms.", s: "Adoro te devote, tr. for Luminaries" },
    { t: "Sight, touch and taste are deceived in Thee; by hearing alone is it safely believed.", s: "Adoro te devote, tr. for Luminaries" },
    { t: "All that I have written seems to me like straw.", s: "his words to his companion Reginald near the end of his life, as reported at his canonization inquiry" },
  ],
  // Longfellow's translation of her bookmark; the Interior Castle in the
  // Benedictines of Stanbrook's translation (1921); her Life tr. David Lewis (1870).
  teresa: [
    { t: "Let nothing disturb thee, Nothing affright thee; All things are passing; God never changeth.", s: "her bookmark, tr. Longfellow" },
    { t: "Patient endurance Attaineth to all things; Who God possesseth In nothing is wanting; Alone God sufficeth.", s: "her bookmark, tr. Longfellow" },
    { t: "I thought of the soul as resembling a castle, formed of a single diamond or a very transparent crystal, and containing many rooms, just as in heaven there are many mansions.", s: "Interior Castle I, tr. Stanbrook" },
    { t: "The soul of the just man is but a paradise, in which, God tells us, He takes His delight.", s: "Interior Castle I, tr. Stanbrook" },
    { t: "The gate by which to enter this castle is prayer and meditation.", s: "Interior Castle I, tr. Stanbrook" },
    { t: "We should fix our eyes on Christ our only good, and on His saints; there we shall learn true humility.", s: "Interior Castle I, tr. Stanbrook" },
    { t: "It is not so essential to think much as to love much.", s: "Interior Castle IV, tr. Stanbrook" },
    { t: "Love does not consist in great sweetness of devotion, but in a fervent determination to strive to please God in all things.", s: "Interior Castle IV, tr. Stanbrook" },
    { t: "This large and ugly worm leaves the cocoon as a lovely little white butterfly.", s: "Interior Castle V, tr. Stanbrook" },
    { t: "Mental prayer is nothing else, in my opinion, but being on terms of friendship with God, frequently conversing in secret with Him Who, we know, loves us.", s: "Life VIII, tr. Lewis" },
    { t: "It seems to me that the garden may be watered in four ways.", s: "Life XI, tr. Lewis" },
    { t: "It is a great evil for a soul to be alone in the midst of such great dangers.", s: "Life VII, tr. Lewis" },
  ],
  // David Lewis's translations: the poems and commentaries (1891 edition, and
  // the Spiritual Canticle of 1909); the Spiritual Maxims (Complete Works, 1864).
  john: [
    { t: "In a dark night, With anxious love inflamed, O, happy lot! Forth unobserved I went, My house being now at rest.", s: "The Dark Night, stanza I, tr. Lewis" },
    { t: "In that happy night, In secret, seen of none, Seeing nought myself, Without other light or guide Save that which in my heart was burning.", s: "The Dark Night, stanza III, tr. Lewis" },
    { t: "That light guided me More surely than the noonday sun.", s: "The Dark Night, stanza IV, tr. Lewis" },
    { t: "O, guiding night; O, night more lovely than the dawn.", s: "The Dark Night, stanza V, tr. Lewis" },
    { t: "Lost to all things and myself, And, amid the lilies forgotten, Threw all my cares away.", s: "The Dark Night, stanza VIII, tr. Lewis" },
    { t: "O Living Flame of Love, That woundest tenderly My soul in its inmost depth!", s: "The Living Flame of Love, tr. Lewis" },
    { t: "O sweet burn! O delicious wound! O tender hand! O gentle touch!", s: "The Living Flame of Love, tr. Lewis" },
    { t: "Where hast Thou hidden Thyself, And abandoned me in my groaning, O my Beloved?", s: "A Spiritual Canticle, tr. Lewis" },
    { t: "The tranquil night At the approaches of the dawn, The silent music, The murmuring solitude.", s: "A Spiritual Canticle, tr. Lewis" },
    { t: "As a thread binds the flowers of a garland, so love knits together and sustains virtues in the soul.", s: "A Spiritual Canticle, tr. Lewis" },
    { t: "If you wish to attain to the possession of Christ, never seek Him without the Cross.", s: "Spiritual Maxims 9, tr. Lewis" },
    { t: "In this life we know God better by what He is not than by what He is.", s: "Spiritual Maxims 23, tr. Lewis" },
    { t: "The more God gives, the more He makes us desire; until He leaves us empty that He may fill us with His blessings.", s: "Spiritual Maxims 45, tr. Lewis" },
    { t: "Herein a man may know whether he really loves God: Is he satisfied with anything less than God?", s: "Spiritual Maxims 60, tr. Lewis" },
    { t: "All our goodness is a loan; God is the owner; God worketh, and His work is God.", s: "Spiritual Maxims 65, tr. Lewis" },
    { t: "That which God intends is to make us God by participation, He being God by nature; as the fire changes everything into fire.", s: "Spiritual Maxims 69, tr. Lewis" },
    { t: "At the close of life you will be examined as to your love.", s: "Spiritual Maxims 70, tr. Lewis" },
    { t: "He who seeks nothing but God walks not in darkness, however blind and poor he may be in his own estimation.", s: "Spiritual Maxims 86, tr. Lewis" },
  ],
  // The Story of a Soul, tr. Thomas N. Taylor (1912), from Project Gutenberg.
  therese: [
    { t: "O Jesus, my Love, at last I have found my vocation. My vocation is love!", s: "Story of a Soul" },
    { t: "In the heart of the Church, my Mother, I will be LOVE!", s: "Story of a Soul" },
    { t: "I mean to try and find a lift by which I may be raised unto God, for I am too tiny to climb the steep stairway of perfection.", s: "Story of a Soul" },
    { t: "I will seek out a means of getting to Heaven by a little way—very short and very straight, a little way that is wholly new.", s: "Story of a Soul" },
    { t: "With me prayer is an uplifting of the heart; a glance towards heaven; a cry of gratitude and love, uttered equally in sorrow and in joy.", s: "Story of a Soul" },
    { t: "I simply tell Our Lord all that I want, and He always understands.", s: "Story of a Soul" },
    { t: "My God, I choose everything, I will not be a Saint by halves.", s: "Story of a Soul" },
    { t: "How shall I show my love, since love proves itself by deeds? Well! The little child will strew flowers.", s: "Story of a Soul" },
    { t: "If a little flower could speak, it seems to me that it would tell us quite simply all that God has done for it.", s: "Story of a Soul" },
    { t: "You see that I am a very little soul, who can only offer very little things to Our Lord.", s: "Story of a Soul" },
    { t: "Now I have no desire left, unless it be to love Jesus even unto folly!", s: "Story of a Soul" },
    { t: "I will spend my Heaven in doing good upon earth.", s: "her words in her last illness, Story of a Soul" },
    { t: "After my death I will let fall a shower of roses.", s: "her words in her last illness, Story of a Soul" },
    { t: "I have never given the Good God aught but love; it is with Love He will repay.", s: "her words in her last illness, Story of a Soul" },
    { t: "I say nothing—I only love Him!", s: "her words in her last illness, Story of a Soul" },
    { t: "My God, I . . . love . . . Thee!", s: "her last words, Story of a Soul" },
  ].map((q) => ({ t: q.t, s: q.s + ", tr. Taylor" })),
};
