"use strict";
// The Fathers from St. John Chrysostom to St. Bede: the public-domain translations of the
// Nicene and Post-Nicene Fathers (as at New Advent), Pusey's Cyril, Sellar's Bede, the 1608
// English of St. Gregory's Life of St. Benedict, and Latin newly translated for Luminaries.
Object.assign(QUOTES, {
  chrysostom: [
    ["Would you do honor to Christ's body? Neglect Him not when naked; do not while here you honor Him with silken garments, neglect Him perishing without of cold and nakedness.", "50"],
    ["For the church is not a gold foundry nor a workshop for silver, but an assembly of angels.", "50"],
    ["Since God has no need at all of golden vessels, but of golden souls.", "50"],
    ["Do you make Him a cup of gold, while you give Him not a cup of cold water?", "50"],
    ["For what is the profit, when His table indeed is full of golden cups, but He perishes with hunger?", "50"],
    ["From beneath, out of the heart, draw forth a voice, make your prayer a mystery.", "19"],
    ["For because He Himself is invisible, He would have your prayer be so likewise.", "19"],
    ["For as in everything it is good to be freed from vainglory, so most especially in prayer.", "19"],
    ["It is not then the giving alms which is required, but the giving as one ought, the giving for such and such an end.", "19"],
    ["Lend unto Him who wants nothing, yet has need for your sake; who feeds all men, yet is an hungered, that you may not suffer famine; who is poor, that you may be rich.", "5"],
    ["For as he who seeks earth before Heaven, will surely lose earth also, so he that prefers Heaven to earth, shall enjoy both in great excellency.", "5"],
  ].map(([t, s]) => ({ t, s: "Homilies on Matthew " + s + ", tr. Prevost, rev. Riddle" })),
  jerome: [
    ["Always have some work on hand, that the devil may find you busy.", "125"],
    ["Make creels of reeds or weave baskets out of pliant osiers.", "125"],
    ["Direct both body and mind to the Lord, overcome wrath by patience, love the knowledge of scripture, and you will no longer love the sins of the flesh.", "125"],
    ["Read the divine scriptures constantly; never, indeed, let the sacred volume be out of your hand.", "52"],
    ["Let us learn upon earth that knowledge which will continue with us in heaven.", "53"],
    ["Love finds nothing hard; no task is difficult to the eager.", "22"],
    ["I used to dread my very cell as though it knew my thoughts; and, stern and angry with myself, I used to make my way alone into the desert.", "22"],
    ["And so, miserable man that I was, I would fast only that I might afterwards read Cicero.", "22"],
    ["You are a follower of Cicero and not of Christ.", "22 (the Judge, in his dream)"],
    ["How can Horace go with the psalter, Virgil with the gospels, Cicero with the apostle?", "22"],
    ["We should rise two or three times in the night, and go over the parts of Scripture which we know by heart.", "22"],
    ["Neither an affected shabbiness nor a stylish smartness becomes a Christian.", "22"],
    ["No meal should be begun without prayer, and before leaving table thanks should be returned to the Creator.", "22"],
  ].map(([t, s]) => ({ t, s: "Letter " + s + ", tr. Fremantle" })),
  cyrilalex: [
    ["Therefore all the words which are read in the Gospels are to be applied to One Person, to One hypostasis of the Word Incarnate.", "Third Letter to Nestorius"],
    ["And since the holy Virgin brought forth corporally God made one with flesh according to nature, for this reason we also call her Mother of God, not as if the nature of the Word had the beginning of its existence from the flesh.", "Third Letter to Nestorius"],
    ["For the Word of God, as we have said already, was made hypostatically one in flesh, yet he is God of all and he rules all; but he is not the slave of himself, nor his own Lord.", "Third Letter to Nestorius"],
    ["Neither will it at all avail to a sound faith to hold, as some do, an union of persons; for the Scripture has not said that the Word united to himself the person of man, but that he was made flesh.", "Letter to Nestorius"],
    ["These words and these decrees we ought to follow, considering what is meant by the Word of God being incarnate and made man.", "Letter to Nestorius"],
  ].map(([t, s]) => ({ t, s: s + ", tr. Percival" })).concat([
    { t: "And if the Father be Light, and the Son likewise Light, how is He less than He?", s: "Commentary on John I, tr. Pusey" },
  ]),
  chrysologus: [
    ["There are three things, brothers, three, by which faith stands, devotion holds firm, and virtue remains: prayer, fasting, mercy.", "Sermon 43"],
    ["What prayer knocks for, fasting obtains, and mercy receives.", "Sermon 43"],
    ["Prayer, mercy and fasting: these three are one, and they give life to one another.", "Sermon 43"],
    ["Fasting is the soul of prayer; mercy is the life of fasting.", "Sermon 43"],
    ["Whoever has only one of these, or does not have them together, has nothing.", "Sermon 43"],
    ["So let the one who prays, fast; let the one who fasts, show mercy.", "Sermon 43"],
    ["We know, brothers, that fasting is the citadel of God, the camp of Christ, the wall of the Spirit, the banner of faith, the sign of chastity, the trophy of holiness.", "Sermon 12"],
    ["Be, O man, be both the sacrifice and the priest of God.", "Sermon 108"],
    ["Make your heart an altar, and so bring your body to God, without fear, as an offering.", "Sermon 108"],
  ].map(([t, s]) => ({ t, s: s + ", tr. for Luminaries" })),
  leo: [
    ["Our Saviour, dearly-beloved, was born today: let us be glad.", "21"],
    ["For there is no proper place for sadness, when we keep the birthday of the Life, which destroys the fear of mortality and brings to us the joy of promised eternity.", "21"],
    ["Christian, acknowledge your dignity, and becoming a partner in the Divine nature, refuse to return to the old baseness by degenerate conduct.", "21"],
    ["Recollect that you were rescued from the power of darkness and brought out into God's light and kingdom.", "21"],
    ["For the birth of Christ is the source of life for Christian folk, and the birthday of the Head is the birthday of the body.", "26"],
    ["But what is it, dearly beloved, to have peace towards God, except to wish what He bids, and not to wish what He forbids?", "26"],
    ["Awake, O man, and recognize the dignity of your nature.", "27"],
    ["Love the purity of a chaste life, because Christ is the Son of a virgin.", "31"],
    ["Set your heart on the profits due to mercy, and traffic in eternal gains.", "17"],
  ].map(([t, s]) => ({ t, s: "Sermon " + s + ", tr. Feltoe" })).concat([
    { t: "For each form does what is proper to it with the co-operation of the other; that is the Word performing what appertains to the Word, and the flesh carrying out what appertains to the flesh.", s: "The Tome (Letter 28), tr. Feltoe" },
  ]),
  gregory: [
    ["The government of souls is the art of arts!", "Pastoral Rule I.1"],
    ["The ruler should be discreet in keeping silence, profitable in speech; lest he either utter what ought to be suppressed or suppress what he ought to utter.", "Pastoral Rule II.4"],
    ["For the word of doctrine penetrates not the mind of one that is in need, if the hand of compassion commends it not to his heart.", "Pastoral Rule II.7"],
    ["For the very virtue of charity, which is the mother and guardian of all virtues, is lost through the vice of impatience.", "Pastoral Rule III.9"],
    ["Those things, in fact, are ours which we love in others, even though we cannot follow them; and what things are loved in us become theirs that love them.", "Pastoral Rule III.10"],
    ["For, indeed, nothing is more fugitive than the heart, which deserts us as often as it slips away through bad thoughts.", "Pastoral Rule III.14"],
  ].map(([t, s]) => ({ t, s: s + ", tr. Barmby" })).concat([
    ["He dwelt alone with himself, in the sight of his Creator, who beholdeth the hearts of all men.", "3"],
    ["Of right she did more which loved more.", "33 (of St. Scholastica)"],
    ["The whole world, gathered as it were together under one beam of the sun, was presented before his eyes.", "35"],
  ].map(([t, s]) => ({ t, s: "Life of St. Benedict " + s + ", tr. 1608, ed. Gardner" }))),
  isidore: [
    ["By prayers we are cleansed; by readings we are taught.", "Sentences III.8"],
    ["Whoever wishes to be always with God ought to pray often, and to read often.", "Sentences III.8"],
    ["For when we pray, we ourselves speak with God; but when we read, God speaks with us.", "Sentences III.8"],
    ["Both are good, if there is time for both; if there is not, it is better to pray than to read.", "Sentences III.8"],
    ["Letters are the tokens of things, the signs of words, and so great is their power that they speak to us, without a voice, the words of those who are absent.", "Etymologies I.3"],
    ["Things are bound fast with letters, so that they do not slip away into forgetting.", "Etymologies I.3"],
    ["None of us knows anything, except the one who learns.", "Etymologies I.1"],
  ].map(([t, s]) => ({ t, s: s + ", tr. for Luminaries" })),
  bede: [
    ["I wholly applied myself to the study of Scripture; and amidst the observance of monastic rule, and the daily charge of singing in the church, I always took delight in learning, or teaching, or writing.", "V.24"],
    ["And I beseech Thee, good Jesus, that to whom Thou hast graciously granted sweetly to drink in the words of Thy knowledge, Thou wilt also vouchsafe in Thy loving-kindness that he may one day come to Thee, the Fountain of all wisdom, and appear for ever before Thy face.", "V.24"],
    ["So this life of man appears for a little while, but of what is to follow or what went before we know nothing at all.", "II.13 (a counsellor of King Edwin)"],
    ["The sparrow, flying in at one door and immediately out at another, whilst he is within, is safe from the wintry tempest.", "II.13 (a counsellor of King Edwin)"],
    ["Cædmon, sing me something.", "IV.24 (to the cowherd, in his dream)"],
    ["Sing the beginning of creation.", "IV.24"],
    ["Now must we praise the Maker of the heavenly kingdom, the power of the Creator and His counsel, the deeds of the Father of glory.", "IV.24 (Cædmon's hymn)"],
  ].map(([t, s]) => ({ t, s: "Ecclesiastical History " + s + ", tr. Sellar" })),
});
